#!/usr/bin/env bash

VERSION="0.0.1-dev"

BUILD_DIR=../../Release/NixxiLang/$VERSION

git config --global user.email "nilphumiphat@outlook.co.th"
git config --global user.name "nilphumiphat212"

build() {
    echo "=========================== Build execute file ==========================="
    local os=$1
    local arch=$2
    local suffix=$3
    local build_path="$BUILD_DIR/$os/nixxilang$suffix"

    export GOOS=$os
    export GOARCH=$arch

    echo "OS: $GOOS"
    echo "Architecture: $GOARCH"    
    
    if [ $os = "windows" ]; then
        go build -o $build_path.exe
        echo "Build success file save to $build_path.exe"
    else
        go build -o $build_path
        echo "Build success file save to $build_path"
    fi
}

cd ./Language/NixxiLang

build windows amd64
build linux 386
build linux arm64 _arm64
build darwin amd64
build darwin arm64 _siilicon
# build android arm _arm
build android arm64 _arm64
# build ios arm _arm
# build ios arm64 _arm64
build js wasm

echo "Push files to release folder"
git add $BUILD_DIR
git commit -m "[NixxiLang][GitActions] Add new files from build"
git pull
git push
