#!/usr/bin/env bash

VERSION="0.0.1-dev"

git config --global user.email "nilphumiphat@outlook.co.th"
git config --global user.name "nilphumiphat212"

cd ./Language/NixxiLang
echo "Build for linux"
export GOOS=linux
export GOARCH=386
go build -o ../../Release/$VERSION/NixxiLangLinux
echo "Build success..."

echo "Build for Windows"
export GOOS=Windows
export GOARCH=386
go build -o ../../Release/$VERSION/NixxiLangWindows.exe
echo "Build success..."

echo "Build for MaCOS"
export GOOS=darwin
export GOARCH=386
go build -o ../../Release/$VERSION/NixxiLangMacOS.exe
echo "Build success..."

echo "Push fils to release folder"
git add ../../Release/$VERSION
git commit -m "[NixxiLang][GitActions] Add new files from build"
git push
