name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.18
    - name: Build for linux
      working-directory: ./Language/NixxiLang
      run: go build -o NixxiLang
    - name: Add to repo
      run: git add . && git commit -m "[NixxiLang][GitActions] Add new execute file from build" && git push
